language: objective-c
osx_image: xcode8.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=TravisEncryptionKeys.xcodeproj
  - SCHEME=TravisEncryptionKeys
  - SDK=iphonesimulator10.3
  matrix:
    - DESTINATION="OS=10.3,name=iPhone SE"     SCHEME="$SCHEME"     SDK="$SDK"     RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6"       SCHEME="$SCHEME"     SDK="$SDK"     RUN_TESTS="NO" POD_LINT="NO"
branches:
 only:
 - master

before_install:
  - rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/TravisEncryptionKeys-*/
  - rvm use $RVM_RUBY_VERSION
  - brew update
  - brew install wget

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build App in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -project "$PROJECT" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test;
    else
      travis_retry xcodebuild -project "$PROJECT" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build;
    fi