language: objective-c
osx_image: xcode8.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=TravisEncryptionKeys.xcodeproj
  - SCHEME=TravisEncryptionKeys
  - SDK=iphonesimulator10.3
  - secure: "Aiysrz5kWRxvXCgOtdjoOqSbNlPk7tUcwIU6aJneL6s9IrM+X6vVdAIM18iDU+8/UTQ40qmAKTGodyVVkW+ywl7dDRkEIGfG6CQc0fPwUfDqTbukIiCAVh/I2PpyzsKjV8EJmbbwKwSd8QyWnI5qzRCxU3pAHF+DvHckgYqidytzp/uB3GmwBf2h04Vp0Ol6cLwJNvQY4InCH63d/zrkUBU6arzwzsgNfro+/QGmKGaw0F7dG45dpIIYO30830a0O5Kfnfkot5KJyf84flUqPtbjGFDvRAdS3LBq+wgLIH6w9K+Ifkqs5dMjLTDhvEyg3cy3xFWvv4t+4eSFMXcxnqEqTEMfFAu9Izk7Ie5kjqp0KVA7Yf6jj1uXWMa7aHPCDOwck4xvvkmKNpWZlC3sNwI/G/Nr1wbFc7LdxR2vw/beAcUBEXXS1wcwI2XfQDNZq9jbBFItEI/t4iVdP3Yo90YZrUPQLh6kGeCTpFXzQ7be4PE3WW3uSgi82gWwjooxswOiy2M18ZWX957vh+5i4s28JAYofgB7HfEEif5JvV8D9auXpAPM9HtpPH5BLM08Yv6ea7Q6Ktvsb1HFHLjbKc4LlE+jZUgbSnUPWnbAe9ohLuhWf3obYK0Bik90zAlLw378jhwbJXj/cn8myIDUiZPSwWirFf8uKM7VN/5gmFs="
  matrix:
    - DESTINATION="OS=10.3,name=iPhone SE"     SCHEME="$SCHEME"     SDK="$SDK"     RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6"       SCHEME="$SCHEME"     SDK="$SDK"     RUN_TESTS="NO" POD_LINT="NO"
branches:
 only:
 - master

before_install:
  - rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/TravisEncryptionKeys-*/
  - rvm use $RVM_RUBY_VERSION
  - wget "$URL" -O AFNetworking.tar.gz
  - tar -xzf AFNetworking.tar.gz

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build App in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -project "$PROJECT" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test;
    else
      travis_retry xcodebuild -project "$PROJECT" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build;
    fi