language: objective-c
osx_image: xcode8.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=TravisEncryptionKeys.xcodeproj
  - SCHEME=TravisEncryptionKeys
  - SDK=iphonesimulator10.3
  - secure: "OH2qU6sSzXOdlKCpdTCvGeR73BLEPfJMNxSOMzloVH3dapbnSq1pyq+5gO8o6Z0b9p0EM2NlUFi+l6aYCsqyZIigpumKE2UxY3GLAz+a2WGPDR6SzNk7U7GSG4VSQlOGq7wn4cDb3Clg0XYuc9XfCQThjYt1bVEm0vTVknG5Mch51xqz21s04VC8asI7tBHgGfmhr1CZ0si1toZcbw996i265701WqT9Su95eBabl5/1SImHfzK7Sg0sG3f/0RdGpcyKYG6IMQ7++23Y1xfAZoAg/BfYq1XqkHU/SDgrSAG22jlpDGx//UubDl6WWkP/RW0HJ9sfaLVtC2Awb0EOZPlqsmTZADFGHYXRVO2aV4dNj3JdPvX+naCjZJa4dRjCjOvEa1yMBnNZkkv4BwsZyAkUIy7QYZSiBj5RV8SbcdxA1YsgyAVZS4/FSlUCuvi640+EGMunHLi0bH9Y8Bgr5ISMkpyUvGWUMOo5dGVw6mH18dvJFU9oCvkGnqqJ39DHR71+1R85bCNhD0kqRzf9cUziZOryikzxQLfpTsj0do7gMf/hpQngQUU3suBFfsB256rdpVNLdYMjYOBUqS4o1ik46ZLmaewlN8xbMb/Z63HqO1myl189Qzw5Btf7q6MZn8qDJOZdy+wBcfCboXg92SfT1lQI+La/HVouWtd6zpg="
  matrix:
    - DESTINATION="OS=10.3,name=iPhone SE"     SCHEME="$SCHEME"     SDK="$SDK"     RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6"       SCHEME="$SCHEME"     SDK="$SDK"     RUN_TESTS="NO" POD_LINT="NO"
branches:
 only:
 - master

before_script:
  - wget "$URL" -O AFNetworking.tar.gz
  - tar -xzf AFNetworking.tar.gz

before_install:
  - rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/TravisEncryptionKeys-*/
  - rvm use $RVM_RUBY_VERSION

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build App in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -project "$PROJECT" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test;
    else
      travis_retry xcodebuild -project "$PROJECT" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build;
    fi